"""Add author_id and parent_commit_id to Commit

Revision ID: 3a35a1f4086d
Revises: 
Create Date: 2025-06-16 15:39:16.294836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a35a1f4086d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('commits', sa.Column('parent_commit_id', sa.Integer(), nullable=True))
    op.drop_constraint('commits_repo_id_fkey', 'commits', type_='foreignkey')
    op.create_foreign_key(None, 'commits', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'commits', 'commits', ['parent_commit_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'commits', 'repositories', ['repo_id'], ['id'], ondelete='CASCADE')
    op.add_column('snapshot', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot', 'is_deleted')
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.create_foreign_key('commits_repo_id_fkey', 'commits', 'repositories', ['repo_id'], ['id'])
    op.drop_column('commits', 'parent_commit_id')
    op.drop_column('commits', 'author_id')
    # ### end Alembic commands ###
