"""Make repo_id nullable and set ondelete SET NULL

Revision ID: 5f7b2bac53d4
Revises: 3a35a1f4086d
Create Date: 2025-06-18 16:13:03.355371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7b2bac53d4'
down_revision: Union[str, None] = '3a35a1f4086d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('log', 'repo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('log_repo_id_fkey', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'repositories', ['repo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key('log_repo_id_fkey', 'log', 'repositories', ['repo_id'], ['id'])
    op.alter_column('log', 'repo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
