"""fix file versioning constraint

Revision ID: 95ba3d5f3959
Revises: 5f7b2bac53d4
Create Date: 2025-06-30 16:05:37.980829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ba3d5f3959'
down_revision: Union[str, None] = '5f7b2bac53d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commits', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'commits', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commits', type_='foreignkey')
    op.drop_column('commits', 'author_id')
    # ### end Alembic commands ###
